### ISSUE TITLE
Comes up with the four greatest features of IPLD

### ISSUE THREAD

**Issue by victorb** [ipld/website#15]
We need to list four of the best features of IPLD.

For each feature we need:

* Title
* One paragraph explanation

**Comment by nicola** [comment]
- number: I really like at the idea of them being 3 (especially because these 3 are already repetitive), or if we use the IPFS template, then it must be a multiple of 2, to put one on each column.
- simplicity: I like not going deep into the technology (dropping terms like merkle-links or hash) could be a stopper for some, the tutorial would cover that.

## Integrity
URLs give no guarantees that the data we receive hasn't been compromised. The IPLD naming system ensures that no one can lie about the data they are serving.

## Distributed
Only the owner of a domain name can serve you the data behind a URL. In IPLD any computer that has the data can help and participate in distributing it.

## Immutability
The content behind URLs can change or disappear, making our links broken or not pointing anymore to what we were expecting. IPLD links cannot mutate, making *** (<- help me out here)

**Comment by victorb** [comment]
Maybe a quick mention that IPLD helps you move from "pointing to where data is" to "pointing to what data you want" which gives you the feature that everyone can serve it. Not sure under which feature though, since it kind of fits all of them in a way.

> (<- help me out here)

"IPLD links cannot mutate, giving you the confidence that the data you request, is the data you receive" or something similar.

**Comment by nicola** [comment]
Your first point is "distributed"

Your last point is "integrity" (and on a very little way relates to immutability too)

**Comment by RichardLitt** [comment]
> URLs give no guarantees that the data we receive hasn't been compromised. The IPLD naming system ensures that no one can lie about the data they are serving.

Maybe:

> URLs give no guarantees that the data we receive hasn't been compromised. The IPLD naming system ensures that what users serve is what they meant to serve.

Using the word "lie" makes it sound malicious. 

---

> The content behind URLs can change or disappear, making our links broken or not pointing anymore to what we were expecting. IPLD links cannot mutate, making *** (<- help me out here)

Maybe: 

> The content behind URLs can change or disappear, breaking links or pointing to the wrong places. IPLD links cannot mutate, so that pointers last forever, and always point the right way. 

A bit poetic, but should work?

**Comment by RichardLitt** [comment]
> URLs give no guarantees that the data we receive hasn't been compromised. The IPLD naming system ensures that no one can lie about the data they are serving.

Should be:

> URIs give no guarantees that the data we receive hasn't been compromised. The IPLD naming system ensures that no data has been changed.

**Comment by victorb** [comment]
* [x] Change Names:
- Secure Links
- Distributed Names
- Immutable Content

- [ ] Add in 'pointing to where data is" to "pointing to what data you want"' to Distributed Names

**Comment by victorb** [comment]
Completed the renaming of the names for the features.

@nicola @RichardLitt however, I'm having difficulties working out the new text for "Distributed Names" so it sounds good. Help please :)

Current one:

        Only the owner of a domain name can serve you
        the data behind a URL. In IPLD any computer
        that has the data can help and participate
        in distributing it

**Comment by RichardLitt** [comment]
A domain’s owner is the only one who can serve you content. With IPLD, anyone who has the data helps with distributing it, too.

**Comment by RichardLitt** [comment]
How does that sound, @nicola?

**Comment by RichardLitt** [comment]
Ping, @nicola

**Comment by nicola** [comment]
Ops it escaped from my sight, that is brilliant!

**Comment by nicola** [comment]
- [x] close this once applied
